### ISSUE TITLE
post method not working in postman.

### ISSUE THREAD

**Issue by yulstewartgurrea** [JuanWilde/WeatherAPI#1]
Hello Juan, I tried testing your work to give me an idea on how this will work. get method is working perfectly but using post method on cities is not working. it displays nothing. can you pls. help how to do it?

**Comment by JuanWilde** [comment]
Hi!
This is the code from a YouTube tutorial that I have created some time ago. You can check it here https://youtu.be/-F7FsNrxdAM and try to find a solution in there!

Let me know if it makes sense for you

**Comment by yulstewartgurrea** [comment]
Ok thank you very much!
